config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: {
    omniauth_callbacks: 'oauth_callbacks',
    confirmations: 'oauth_confirmations'
  }
  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only:%i[index] do
        get :me, on: :collection
      end
      resources :questions, only:%i[index show create update destroy] do
        resources :answers, only:%i[index show create update destroy], shallow: true
      end
    end
  end


  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_destroy
    end
  end

  concern :commentable do
    resources :comments, only: %i[create]
  end

  resources :questions, concerns: %i[votable commentable]  do
    resources :answers, shallow: true, concerns: %i[votable commentable]  do
      patch :best, on: :member
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end
  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index

  get :search, to: 'search#results'

  mount ActionCable.server => '/cable'

end

app/models/question.rb
class Question < ApplicationRecord

  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :award, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :user

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :award, reject_if: :all_blank

  validates :body, :title, presence: true

  after_create :subscribe_to_answers

  private

  def subscribe_to_answers
    subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource class: Question
  before_action :set_question, only: %i[show update destroy]
  after_action :publish_question, only: :create

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionCollectionSerializer
  end

  def show
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)
    if @question.save
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, @question
    if @question.update(question_params)
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @question
    @question.destroy!
    render json: {}, status: :ok
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.permit(:title, :body)
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: %i[show update destroy]
  after_action :publish_question, only: %i[create]

  authorize_resource

  def new
    @question = current_user.questions.new
    @question.build_award
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  def update
    @question.update(question_params)
  end

  private

  def set_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body,
      files: [],
      award_attributes: [:title, :image],
      links_attributes: [:name, :url, :_destroy, :id])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: { question: @question }
      )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
p= link_to question.title, question

app/views/questions/_question_show.html.slim
#question data-question-id=@question.id
h1= @question.title
p= @question.body
. class="question-#{@question.id}"
  .vote
    = render partial: 'shared/vote', locals: { resource: @question }

= render 'shared/links', resource: @question

- if @question.files.attached?
  - @question.files.each do |file|
    div id=file.id class='file'
      p= link_to file.filename.to_s, url_for(file)
      - if can? :destroy, file
        =link_to 'Delete file',
                     file_path(file),
                     method: :delete,
                     remote: true

- if can?(:create, Subscription)
  = render 'subscriptions/subscription_block', resource: @question

.question-comments
  = render 'comments/comments_block', resource: @question

app/views/questions/index.html.slim
.questions-list
  = render @questions

p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true

  p Links:
  p
    = f.fields_for :links do |l|
      = render 'shared/link_fields', f: l
    = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

  p Award
  p
    = f.fields_for :award do |a|
      = a.label :title, 'Award title'
      br
      = a.text_field :title
      = a.label :image, 'Award picture'
      br
      = a.file_field :image

  p= f.submit 'Ask'

app/views/questions/show.html.slim
- cache @question do

  .question-errors
    = render 'shared/errors', resource: @question

  .question
   = render 'question_show'

  .question-link
    = form_with model: @question, class: 'hidden', html: { id: "edit-question" } do |f|
      = f.label :body, 'Edit question'
      = f.text_area :body
      .edit-question-links
        = f.fields_for :links do |l|
          = render 'shared/link_fields', f: l
        = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
      = f.submit 'Save'

    - if current_user&.author?(@question)
      p= link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: @question.id }
      p= link_to 'Delete question',
                   question_path(@question),
                   method: :delete,
                   data: { confirm:'You sure delete' }

  .answer-errors
    = render 'shared/errors', resource: @answer

  .answers
    = render @question.answers

  = form_with model: [@question, @answer], class: 'new-answer' do |f|
    = f.label :body, 'Your answer'
    = f.text_area :body
    = f.label :files
    = f.file_field :files, multiple: true
    p Links:
    p
      = f.fields_for :links do |l|
        = render 'shared/link_fields', f: l
      = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

    = f.submit 'Add answer'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.question').html('<%= j render 'question_show' %>')
  $('#edit-question').addClass('hidden');
  $('.edit-question-link').show();
<% end %>