config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: {
    omniauth_callbacks: 'oauth_callbacks',
    confirmations: 'oauth_confirmations'
  }
  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only:%i[index] do
        get :me, on: :collection
      end
      resources :questions, only:%i[index show create update destroy] do
        resources :answers, only:%i[index show create update destroy], shallow: true
      end
    end
  end


  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_destroy
    end
  end

  concern :commentable do
    resources :comments, only: %i[create]
  end

  resources :questions, concerns: %i[votable commentable]  do
    resources :answers, shallow: true, concerns: %i[votable commentable]  do
      patch :best, on: :member
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end
  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index

  get :search, to: 'search#results'

  mount ActionCable.server => '/cable'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def results
    @query = query_params
    @results = Services::Search.new.call(@query)
    head :bad_request unless @results
  end

  private

  def query_params
    params.permit(:query, :scope)
  end
end

app/views/search/_answer.html.slim
p = resource.body
= link_to 'Question link', question_path(resource.question)

app/views/search/_comment.html.slim
p= resource.body
- if resource.commentable.class == Answer
  = link_to 'Question link', question_path(resource.commentable.question)
- else
  = link_to 'Question link', question_path(resource.commentable)

app/views/search/_question.html.slim
p= link_to resource.title, question_path(resource)

app/views/search/_search_form.html.slim
= form_with url: search_path,
                 method: :get,
                 local: true do |f|

  = f.label :query
  = f.text_area :query

  = f.select(:scope,
               [['All', 'thinking_sphinx'],
                ['Question', 'question'],
                ['Answer', 'answer'],
                ['Comment', 'comment'],
                ['User', 'user']])

  = f.submit 'Search'

app/views/search/_user.html.slim
p = resource.email

app/views/search/results.html.slim
h1 Search results
- @results.each do |result|
  = render partial: result.class.to_s.downcase, locals: { resource: result }