config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: {
    omniauth_callbacks: 'oauth_callbacks',
    confirmations: 'oauth_confirmations'
  }
  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only:%i[index] do
        get :me, on: :collection
      end
      resources :questions, only:%i[index show create update destroy] do
        resources :answers, only:%i[index show create update destroy], shallow: true
      end
    end
  end


  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :vote_destroy
    end
  end

  concern :commentable do
    resources :comments, only: %i[create]
  end

  resources :questions, concerns: %i[votable commentable]  do
    resources :answers, shallow: true, concerns: %i[votable commentable]  do
      patch :best, on: :member
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end
  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :awards, only: :index

  get :search, to: 'search#results'

  mount ActionCable.server => '/cable'

end

app/models/answer.rb
class Answer < ApplicationRecord

  include Votable
  include Commentable

  default_scope { order(best: :desc) }

  has_many :links, dependent: :destroy, as: :linkable
  belongs_to :question, touch: true
  belongs_to :user

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true

  after_create :sent_notification

  def best!
    Answer.transaction do
      question.answers.update_all(best: false)
      update!(best: true)
      question.award&.update!(user: user)
    end
  end

  private

  def sent_notification
    SubscriptionJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :set_answer, only: %i[update destroy best]
  after_action :publish_answer, only: :create

  authorize_resource

  def create
    @answer = question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def destroy
    @answer.destroy
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def best
    @answer.best!
    @question = @answer.question
  end

  private

  def question
    @question ||= Question.find(params[:question_id])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "questions/#{@answer.question_id}/answers",
      answer: @answer,
      author_id: @answer.user_id,
      links: links_data,
      files: files_data
      )
  end

  def links_data
    @answer.links.each_with_object([]) do |link, links|
      if link.gist_url?
        GistService.new(link).content.each do |gist|
          links << { name: gist[:file_name], url: gist[:file_content] }
        end
      else
        links << { name: link.name, url: link.url }
      end
    end
  end

  def files_data
    @answer.files.each_with_object([]) do |file, files|
      files << { url: url_for(file), name: file.filename.to_s }
    end
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [],
      links_attributes: [:name, :url, :_destroy, :id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource class: Answer
  before_action :set_answer, only: %i[show update destroy]
  after_action :publish_answer, only: :create

  def index
    @answers = question.answers
    authorize! :index, @answers
    render json: @answers, each_serializer: AnswerCollectionSerializer
  end

  def show
    @answer = Answer.find(params[:id])
    authorize! :show, @answer
    render json: @answer
  end

  def create
    @answer = question.answers.new(answer_params)
    @answer.user = current_resource_owner
    if @answer.save
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    @answer = Answer.find(params[:id])
    authorize! :update, @answer
    if @answer.update(answer_params)
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    authorize! :destroy, @answer
    @answer.destroy!
    render json: {}, status: :ok
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.permit(:body)
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "questions/#{@answer.question_id}/answers",
      answer: @answer,
      author_id: @answer.user_id,
      links: [],
      files: []
      )
  end


  def question
    @question ||= Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div id= "answer-#{answer.id}"
  -if answer.persisted?
    - cache answer do
      p= answer.body
      . class="answer-#{answer.id}"
        .vote
          = render partial: 'shared/vote', locals: { resource: answer }

      = render 'shared/links', resource: answer

      - if can? :update, answer
        p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      - if can? :destroy, answer
        = link_to 'Delete answer',answer, method: :delete, remote: true
      br
      - if can? :best, answer
        =link_to 'Mark as best', best_answer_path(answer), remote: true, class: 'mark-as-best', data: { answer_id: answer.id }, method: :patch

      = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
        = f.label :body, 'Your answer'
        = f.text_area :body
        .edit-answer-links
          = f.fields_for :links do |l|
            = render 'shared/link_fields', f: l
          = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true
        = f.submit 'Save'

    - if answer.files.attached?
      - answer.files.each do |file|
        div id=file.id class='file'
          p= link_to file.filename.to_s, url_for(file)
          - if can? :destroy, file
            =link_to 'Delete file',
                         file_path(file),
                         method: :delete,
                         remote: true

-if answer.persisted?
  .answer-comments
    = render 'comments/comments_block', resource: answer

app/views/answers/best.js.erb
<% if @answer.best %>
  $('.answers').html('<%= j render @question.answers %>');
  $('<%= "#answer-#{@answer.id}" %>').addClass('best');
  $(".mark-as-best").removeClass('hidden');
  $(".mark-as-best[data-answer-id='<%= @answer.id %>']").addClass('hidden');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
  $('<%= "#answer-#{@answer.id}" %>').remove()
<% end %>

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('<%= "#answer-#{@answer.id}" %>').html('<%= j render @answer %>')
<% end %>